### ISSUE TITLE
Fail to build output using build instructions (on Linux)

### ISSUE THREAD

**Issue by gnash117** [openconnectivityfoundation/DeviceBuilder#15]
Building using the following command:

    ./DeviceBuilder_C++IotivityServer.sh DeviceBuilderInputFormat-file-examples/input-lightdevice-dimming.json ../lightdevice-dimming "oic.d.light"

I get the following errors

```
input file:    DeviceBuilderInputFormat-file-examples/input-lightdevice-dimming.json
output folder: ../lightdevice-dimming
~/DeviceBuilder ~/DeviceBuilder
fatal: destination path 'core' already exists and is not an empty directory.
~/DeviceBuilder
copying ../Core/swagger2.0/*.swagger.json ../IoTDataModels/*
cp: cannot stat '../Core/swagger2.0/*.swagger.json': No such file or directory
creating ../lightdevice-dimming
python3: can't open file './src/deviceBuilder.py': [Errno 2] No such file or directory
./DeviceBuilder_C++IotivityServer.sh: line 112: wb-swagger: command not found
*************************
***  swag2cbor (v1)   ***
*************************
file        : ../lightdevice-dimming/out_introspection_merged.swagger.json
cbor        : None
Traceback (most recent call last):
  File "./src/swag2cbor.py", line 57, in <module>
    swagger_raw = open(args.file, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '../lightdevice-dimming/out_introspection_merged.swagger.json'
cp: cannot stat '../lightdevice-dimming/out_introspection_merged.swagger.json.cbor': No such file or directory
************************
swagger2x  20171123
************************
file          : ../lightdevice-dimming/out_codegeneration_merged.swagger.json
out_dir       : ../lightdevice-dimming/code
schemadir     : .
template      : C++IotivityServer
template_dir  : ../swagger2x/src/templates

uuid          : 9b8fadc6-1e57-4651-bab2-e268f89f3ea7
device type   : oic.d.light
manufacturer  : ocf

json file does not exist: ../lightdevice-dimming/out_codegeneration_merged.swagger.json
error in  ../lightdevice-dimming/out_codegeneration_merged.swagger.json
Traceback (most recent call last):
  File "../swagger2x/src/swagger2x.py", line 719, in <module>
    json_data = load_json_schema(args.swagger)
  File "../swagger2x/src/swagger2x.py", line 83, in load_json_schema
    linestring = open(full_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '../lightdevice-dimming/out_codegeneration_merged.swagger.json'
*************************
***  swag2cbor (v1)   ***
*************************
file        : ../lightdevice-dimming/code/svr_server.json
cbor        : None
Traceback (most recent call last):
  File "./src/swag2cbor.py", line 57, in <module>
    swagger_raw = open(args.file, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '../lightdevice-dimming/code/svr_server.json'
cp: cannot stat '../lightdevice-dimming/code/svr_server.json.cbor': No such file or directory
cp: cannot stat '../lightdevice-dimming/code/svr_server.json.cbor': No such file or directory
```
Linux is a case sensitive OS:

    python3: can't open file './src/deviceBuilder.py': [Errno 2] No such file or directory

search the code for instances of `src/deviceBuilder.py`

**Change**
DeviceBuilder_C++IotivityServer.sh
line 56:
from:  `DeviceBuilder=./src/deviceBuilder.py`
to `DeviceBuilder=./src/DeviceBuilder.py`

test/test.sh
line 4
from:  `DeviceBuilder=./src/deviceBuilder.py`
to `DeviceBuilder=./src/DeviceBuilder.py`

**Comment by WAvdBeek** [comment]
solved
